const count = (list) => (Array.isArray(list) ? list.length : 0);

export const buildFilm = (scenario) => [
  { id: 'home', kind: 'home', surface: 'Home', act: '01 — FRAME', title: 'The work starts in plain language.', story: scenario.intent, caption: `${scenario.owner} names the outcome and constraints. Home assembles ${count(scenario.people)} people and ${count(scenario.agents)} specialists without turning the request into a technical spec.`, state: `INTENT::ROUTED — OWNER::${scenario.owner.toUpperCase()} — AUTHORITY::HUMAN` },
  { id: 'library', kind: 'library', surface: 'Library', act: '02 — GROUND', title: 'Every answer begins with retrievable evidence.', story: scenario.libraryQuery || scenario.trigger, caption: `Hybrid search ranks exact identifiers and semantic context across ${count(scenario.knowledge)} permitted sources: ${(scenario.knowledge || []).slice(0, 3).join(' · ')}.`, state: `RAG::HYBRID — SOURCES::${count(scenario.knowledge)} — CITATIONS::REQUIRED` },
  { id: 'chat', kind: 'chat', surface: 'Chat', act: '03 — COORDINATE', title: 'People and agents share one moving thread.', story: scenario.message, caption: `${(scenario.people || []).join(', ')} remain present while specialists synthesize evidence, expose disagreement, and escalate the decision.`, state: `CHANNEL::${String(scenario.channel).toUpperCase()} — PRESENCE::${count(scenario.people)} — MERGE::LIVE` },
  { id: 'apps', kind: 'apps', surface: 'Apps', act: '04 — COMPOSE', title: 'Capabilities become a governed workflow.', story: `${scenario.workflow} connects ${(scenario.apps || scenario.agents).slice(0, 3).join(', ')}.`, caption: 'Apps packages retrieval, analysis, action, and approval into reusable operating tools with explicit boundaries.', state: `WORKFLOW::COMPILED — SPECIALISTS::${count(scenario.agents)} — GATES::ENFORCED` },
  { id: 'code', kind: 'code', surface: 'Code', act: '05 — COMPUTE', title: 'When code is useful, it stays inside its boundary.', story: scenario.codeTask, caption: `${scenario.codeFile} runs with scoped credentials, isolated execution, retained artifacts, and no production write until approval.`, state: `SANDBOX::ISOLATED — EGRESS::SCOPED — ARTIFACTS::RETAINED` },
  { id: 'browser', kind: 'browser', surface: 'Browser', act: '06 — VERIFY', title: 'Current external evidence joins the record.', story: scenario.browserTitle, caption: `Browser opens approved sources and captures the facts that can change the decision: ${(scenario.browserItems || []).join('; ')}.`, state: `SOURCE::APPROVED — CAPTURES::${count(scenario.browserItems)} — FRESHNESS::VISIBLE` },
  { id: 'computer', kind: 'computer', surface: 'Computer', act: '07 — EXECUTE', title: 'The system can act, while people keep the boundary.', story: scenario.computerTask, caption: `${(scenario.computerSteps || []).join(' → ')}. Every action is observable, interruptible, and recorded before the next step begins.`, state: `SESSION::SUPERVISED — CONTROL::INTERRUPTIBLE — WRITE::CHECKPOINTED` },
  { id: 'teamspaces', kind: 'teamspaces', surface: 'Teamspaces', act: '08 — DECIDE', title: 'The decision becomes shared organizational memory.', story: scenario.checkpoint, caption: `${scenario.outcome} Pages, owners, evidence, approvals, and execution state remain in ${scenario.teamspace} as one reconstructable line.`, state: `CHECKPOINT::HUMAN — OUTCOME::${String(scenario.metric).toUpperCase()} — AUDIT::WRITTEN` }
];